iterations: 100_000_000
threadCount: 16
fieldWidth: 21
fieldHeight: 27
blockedArea:
  posx: 6
  posy: 5
  width: 8
  height: 10
# 487 possible empty fields
optionalWordList:
wordList:
  - MAR
  - SALZ
  - NORDSEE
  - WELLENGANG
  - SEETANG
  - RUHE
  - CHOR
  - MUNDHARMONIKA
  - VILLA-ELYSEE
  - ROBBE
  - SMUTJE
  - RONDE-PLATE
  - HEIDSCHNUCKEN
  - KUTTER
  - FLUT
  - EBBE
  - DLRG
  - HAI
  - EMS
  - MOOI
  - AKKERMANN
  - WETTER
  - WINDPARK
  - WATTENMEER
  - WAL
  - HOCHSEEKLIMA
  - GEZEITENLAND
  - LACHMÃ–WE
  - RIFF
  - FERIEN
  - GELD
  - FESTLAND
  - FAMILIE
  - OPFER
  - SONNENCREME
  - SONNENBRAND
  - RAMONA
  - SUDOKU
  - PFERD
  - AIOLI
  - CHRIS
  - VERLEIH
  - SCHNITZEL
  - YACHT
  - ERNEST
  - KAFFEE
  - EBIKE
  - FOTO
  - SURFEN
  - ANGELN
  - AQUARIUM
  - MORITZ
  - AHOI
